name: Build and Deploy

permissions:
  contents: write
  
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "adrian.bucur94@proton.me"
          git config --global user.name "rebooted943"

      - name: Install dependencies
        working-directory: poke-cards-react
        run: npm install

      - name: Build project
        working-directory: poke-cards-react
        run: npm run build

      - name: Deploy to GitHub Pages
        working-directory: poke-cards-react
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy
